#!/bin/sh
############################################################################################
# Title: ip_info
# Author: Adam Mocarski
# Description: This script takes 2 parameters.  The first is the interface to search.
#					This will almost always just be "eth0"
#					Second parameter is the field to return
#					It must be the same name as one of the fields ifconfig returns
#					For example:
#						ip_info eth0 "inet addr"
#					will return the ipv4 address
#
# Copyright (C) AMETEK Programmable Power, 2014
############################################################################################
# Get the interface from ifconfig
exec ifconfig $1 | \
# Extract the selected parameter
sed -n "/$2/s/^.*$2[:[:space:]]*\([[:alnum:]]\{1,3\}\([:.][[:alnum:]]*\)*\).*$/\1/p"
